[package]
name = "aws-lambda-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.4.1"
tokio = "1.15.0"
serde = "1.0.132"
serde_json = "1.0.73"

